%% STEP 19.5 - BER COMPARISON
% Active-Subcarrier OFDM
% No Equalization vs Known-Channel ZF vs Pilot-Based LS-ZF

clc;
clear;
close all;

fprintf('\n');
fprintf('============================================\n');
fprintf(' STEP 19.5: 3-SYSTEM BER COMPARISON\n');
fprintf('============================================\n');

%% System Parameters

Nfft = 64;
cpLength = 16;

M = 4;
bitsPerSymbol = log2(M);

numOFDMSymbols = 1000;

snrRange = 0:2:20;

%% Active Subcarriers

activeSubcarriers = [-26:-1 1:26];

activeIndices = ...
    mod(activeSubcarriers,Nfft) + 1;

numActiveSubcarriers = ...
    length(activeIndices);

%% Multipath Channel

pathDelays = [0 2 4];

pathGains = [1.00 0.50 0.25];

channelImpulseResponse = ...
    zeros(max(pathDelays)+1,1);

for p = 1:length(pathDelays)

    channelImpulseResponse( ...
        pathDelays(p)+1) = pathGains(p);

end

%% Channel Frequency Response

channelFrequencyResponse = ...
    fft(channelImpulseResponse,Nfft);

%% Data Generation

numQPSKSymbols = ...
    numActiveSubcarriers * numOFDMSymbols;

numBits = ...
    numQPSKSymbols * bitsPerSymbol;

rng(1000);

txBits = randi([0 1],numBits,1);

txSymbolIndices = ...
    bi2de( ...
    reshape(txBits,bitsPerSymbol,[]).', ...
    'left-msb');

txQPSK = ...
    pskmod(txSymbolIndices,M,pi/4);

%% OFDM Transmitter

txGrid = zeros(Nfft,numOFDMSymbols);

txGrid(activeIndices,:) = ...
    reshape( ...
    txQPSK, ...
    numActiveSubcarriers, ...
    numOFDMSymbols);

txIFFT = ...
    ifft(txGrid,Nfft,1);

txWithCP = [
    txIFFT(end-cpLength+1:end,:);
    txIFFT
];

txFrame = txWithCP(:);

%% Pilot Generation

pilotSymbols = ones(numActiveSubcarriers,1);

pilotGrid = zeros(Nfft,1);

pilotGrid(activeIndices) = ...
    pilotSymbols;

pilotIFFT = ...
    ifft(pilotGrid,Nfft);

pilotWithCP = [
    pilotIFFT(end-cpLength+1:end);
    pilotIFFT
];

%% BER Arrays

berNoEqualization = ...
    zeros(length(snrRange),1);

berKnownZF = ...
    zeros(length(snrRange),1);

berPilotLSZF = ...
    zeros(length(snrRange),1);

%% SNR Loop

for s = 1:length(snrRange)

    currentSNR = snrRange(s);

    %% -------------------------------
    % DATA THROUGH MULTIPATH + AWGN
    % -------------------------------

    rxDataMultipath = ...
        filter( ...
        channelImpulseResponse, ...
        1, ...
        txFrame);

    rxDataNoisy = ...
        awgn( ...
        rxDataMultipath, ...
        currentSNR, ...
        'measured');

    %% Receiver

    rxMatrix = ...
        reshape( ...
        rxDataNoisy, ...
        Nfft+cpLength, ...
        numOFDMSymbols);

    rxNoCP = ...
        rxMatrix(cpLength+1:end,:);

    rxFFT = ...
        fft(rxNoCP,Nfft,1);

    %% Active Subcarriers

    rxActiveData = ...
        rxFFT(activeIndices,:);

    %% ==================================
    % SYSTEM 1: NO EQUALIZATION
    % ==================================

    rxNoEQ = ...
        rxActiveData(:);

    rxSymbolsNoEQ = ...
        pskdemod( ...
        rxNoEQ, ...
        M, ...
        pi/4);

    rxBitsNoEQMatrix = ...
        de2bi( ...
        rxSymbolsNoEQ, ...
        bitsPerSymbol, ...
        'left-msb');

    rxBitsNoEQ = ...
        reshape( ...
        rxBitsNoEQMatrix.', ...
        [],1);

    berNoEqualization(s) = ...
        sum(txBits ~= rxBitsNoEQ) ...
        / numBits;

    %% ==================================
    % SYSTEM 2: KNOWN-CHANNEL ZF
    % ==================================

    knownActiveChannel = ...
        channelFrequencyResponse(activeIndices);

    rxKnownZF = zeros(size(rxActiveData));

    for k = 1:numActiveSubcarriers

        rxKnownZF(k,:) = ...
            rxActiveData(k,:) ...
            ./ knownActiveChannel(k);

    end

    rxKnownZFSerial = ...
        rxKnownZF(:);

    rxSymbolsKnownZF = ...
        pskdemod( ...
        rxKnownZFSerial, ...
        M, ...
        pi/4);

    rxBitsKnownZFMatrix = ...
        de2bi( ...
        rxSymbolsKnownZF, ...
        bitsPerSymbol, ...
        'left-msb');

    rxBitsKnownZF = ...
        reshape( ...
        rxBitsKnownZFMatrix.', ...
        [],1);

    berKnownZF(s) = ...
        sum(txBits ~= rxBitsKnownZF) ...
        / numBits;

    %% ==================================
    % PILOT TRANSMISSION
    % ==================================

    rxPilotMultipath = ...
        filter( ...
        channelImpulseResponse, ...
        1, ...
        pilotWithCP);

    rxPilotNoisy = ...
        awgn( ...
        rxPilotMultipath, ...
        currentSNR, ...
        'measured');

    %% Pilot Receiver

    rxPilotNoCP = ...
        rxPilotNoisy(cpLength+1:end);

    receivedPilotFrequency = ...
        fft(rxPilotNoCP,Nfft);

    %% Pilot-Based LS Estimation

    estimatedChannel = ...
        receivedPilotFrequency(activeIndices) ...
        ./ pilotSymbols;

    %% ==================================
    % SYSTEM 3: PILOT LS + ZF
    % ==================================

    rxPilotLSZF = ...
        zeros(size(rxActiveData));

    for k = 1:numActiveSubcarriers

        rxPilotLSZF(k,:) = ...
            rxActiveData(k,:) ...
            ./ estimatedChannel(k);

    end

    rxPilotLSZFSerial = ...
        rxPilotLSZF(:);

    rxSymbolsPilotLSZF = ...
        pskdemod( ...
        rxPilotLSZFSerial, ...
        M, ...
        pi/4);

    rxBitsPilotLSZFMatrix = ...
        de2bi( ...
        rxSymbolsPilotLSZF, ...
        bitsPerSymbol, ...
        'left-msb');

    rxBitsPilotLSZF = ...
        reshape( ...
        rxBitsPilotLSZFMatrix.', ...
        [],1);

    berPilotLSZF(s) = ...
        sum(txBits ~= rxBitsPilotLSZF) ...
        / numBits;

    %% Display

    fprintf( ...
        'SNR = %2d dB   No-EQ = %.8f   Known-ZF = %.8f   Pilot-LS-ZF = %.8f\n', ...
        currentSNR, ...
        berNoEqualization(s), ...
        berKnownZF(s), ...
        berPilotLSZF(s));

end

%% BER Comparison Plot

figure;

semilogy( ...
    snrRange, ...
    berNoEqualization, ...
    '-o', ...
    'LineWidth',1.5);

hold on;

semilogy( ...
    snrRange, ...
    berKnownZF, ...
    '-s', ...
    'LineWidth',1.5);

semilogy( ...
    snrRange, ...
    berPilotLSZF, ...
    '-^', ...
    'LineWidth',1.5);

grid on;

xlabel('SNR (dB)');

ylabel('BER');

title('Active-Subcarrier OFDM BER Comparision');

legend( ...
    'No Equalization', ...
    'Known-Channel ZF', ...
    'Pilot-Based LS + ZF', ...
    'Location','southwest');

fprintf('\nBER comparison graph generated successfully.\n');

%% Final Summary

fprintf('\n============================================\n');
fprintf(' STEP 19.5 SUMMARY\n');
fprintf('============================================\n');

fprintf('FFT Size             : %d\n',Nfft);

fprintf('Active Subcarriers   : %d\n', ...
    numActiveSubcarriers);

fprintf('Modulation           : QPSK\n');

fprintf('Channel              : Multipath + AWGN\n');

fprintf('Equalization Methods : None / Known-ZF / Pilot-LS-ZF\n');

fprintf('\nSTEP 19.5 completed successfully.\n');
